// <auto-generated />
using EulerSolver.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EulerSolver.Migrations
{
    [DbContext(typeof(EulerSolverDataContext))]
    [Migration("20180101211945_RevisedDb")]
    partial class RevisedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EulerSolver.Model.FactorialResult", b =>
                {
                    b.Property<int>("FactorialResultId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count1");

                    b.Property<int>("Count2");

                    b.Property<int>("Count3");

                    b.Property<int>("Count4");

                    b.Property<int>("Count5");

                    b.Property<int>("Count6");

                    b.Property<int>("Count7");

                    b.Property<int>("Count8");

                    b.Property<int>("Count9");

                    b.Property<string>("FactorialSum");

                    b.Property<int>("FactorialSumCount1");

                    b.Property<int>("FactorialSumCount2");

                    b.Property<int>("FactorialSumCount3");

                    b.Property<int>("FactorialSumCount4");

                    b.Property<int>("FactorialSumCount5");

                    b.Property<int>("FactorialSumCount6");

                    b.Property<int>("FactorialSumCount7");

                    b.Property<int>("FactorialSumCount8");

                    b.Property<int>("FactorialSumCount9");

                    b.Property<bool>("IsMatch");

                    b.HasKey("FactorialResultId");

                    b.ToTable("FactorialResults");
                });
#pragma warning restore 612, 618
        }
    }
}
