<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ProjectEulerSolver.Cli</RootNamespace>
    <AssemblyName>euler</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectEulerSolver\ProjectEulerSolver.csproj" />
  </ItemGroup>

</Project>
